### ISSUE TITLE
Webpack v4 compatibility warning

### ISSUE THREAD

**Issue by astorije** [danielholmes/relay-compiler-webpack-plugin#28]
With Webpack v4, I am getting:

```
$ node --trace-deprecation ./node_modules/.bin/webpack
(node:79941) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at RelayCompilerWebpackPlugin.apply ([...]/node_modules/relay-compiler-webpack-plugin/dist/index.js:124:14)
    at webpack ([...]/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions ([...]/node_modules/webpack-cli/bin/webpack.js:436:16)
    at yargs.parse ([...]/node_modules/webpack-cli/bin/webpack.js:510:3)
    at Object.parse ([...]/node_modules/webpack-cli/node_modules/yargs/yargs.js:543:18)
    at [...]/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> ([...]/node_modules/webpack-cli/bin/webpack.js:512:3)
```

See https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202 and https://github.com/webpack/tapable:

> The `plugin` method on tapable objects is theoretically backward-compatible, but it causes a deprecation warning, so plugins should consider switching to `tap` instead.

**Comment by danielholmes** [comment]
Solved with https://github.com/danielholmes/relay-compiler-webpack-plugin/releases/tag/v0.10.0
